sudo: false
language: node_js
node_js: '5'
addons:
  postgresql: '9.4'
before_script:
- bash install.sh
script:
- source env.sh && npm run test
notifications:
  slack: devops-training-spb:kfjTXFxdFQxyBbAJ0UtYVqOe
deploy:
  pp: dry-tundra-31235
  provider: heroku
  api_key:
    secure: AoIPISUzmp0VprLINa7h/QQFs7PYuqFou2MTgLV+LgkeT3vZuuPZyZqNC+hcMHwRc5bafaLECcIjcX0BqwIiQI9YtW1Rg/cALOt1PH8h/5hUDzCqQZG5xnAjq0esFEvIfuiPJaUIFw0gFGOdxavctDbiIYiXDSUg4tEObdYs3qaqeDQPZkXSresTUHpuXY7aCZekMTP/W2FGdQWP1P24ieZVK6i7UaWcupkEex/L9IyuiQHkJ+9mnOmzO5QVX/2PWb0aEp51fmaFZIbpYca6LY41kwye4n0T7ITjwjNETzXAIk3F1sUmrDyGZuK2KlsgubJMofTbVyLqGqdr5dC121bQR0u63mKilFlVk+CXS2EQzk6YoPqc9vXu3jfYotKdS8SdistLZZhn0HlAWAVF82HY0apiHfm0TypoWn6Y99uRyNK03W6GSzBVsNGhl0h/LAQYEK6RNP0PaQA910KuhdGDHdd5y5kTkq9eoWkFL68CprQaTWFVVWIXl5Q8Nn4teFRIWDFgBUCl3ZgTAEes1o6PaTA4s+b+mWKgYt6v6YmzBYkUZ16m4vne6eznWoj+bG5nGUnBk+y7gt7juwteS18oybY5C8p11y062cWHaC90NTIe7wY/6+CxuZ2jQB1lRP3FWoMevaKTtjkT8S1CM1DVaU/iQdVfd1lh6sM+8fA=
